name: CI-CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # 1. Install Maven
      - name: Install Maven
        run: |
          sudo apt update
          sudo apt install -y maven

      # 2. Set up Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # 3. Build & Test (Sonar optional)
      - name: Build and Test
        run: |
          mvn clean verify
